id: whois_test
version: -1
fromversion: 4.1.0
name: whois_test
description: This is a test playbook for Whois. It will retrieve details for google.com
  and confirm the domain name is the same.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 48f0c48e-a802-4f2e-84de-008932b465c3
    type: start
    task:
      id: 48f0c48e-a802-4f2e-84de-008932b465c3
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
  "1":
    id: "1"
    taskid: 266cb948-64e7-43fd-80a2-e57ce8421af0
    type: regular
    task:
      id: 266cb948-64e7-43fd-80a2-e57ce8421af0
      version: -1
      name: whois
      description: Provides data enrichment for Domains, URLs, and IP addresses.
      script: Whois|||whois
      type: regular
      iscommand: true
      brand: Whois
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      query:
        simple: google.co.uk
      retry-count:
        simple: "5"
      retry-interval:
        simple: "30"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
  "2":
    id: "2"
    taskid: a3fb8d0e-b111-4e6b-895d-0fd33558bd89
    type: condition
    task:
      id: a3fb8d0e-b111-4e6b-895d-0fd33558bd89
      version: -1
      name: Check results
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: ${Domain.Name}
            iscontext: true
          right:
            value:
              simple: google.co.uk
      - - operator: isEqualString
          left:
            value:
              simple: Domain.Whois.QueryStatus
            iscontext: true
          right:
            value:
              simple: Success
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
  "3":
    id: "3"
    taskid: f5017f04-7966-4244-80a1-ab706d403210
    type: regular
    task:
      id: f5017f04-7966-4244-80a1-ab706d403210
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
  "4":
    id: "4"
    taskid: 5d44058f-594f-44b7-8f2e-e74bd1b9d5c9
    type: regular
    task:
      id: 5d44058f-594f-44b7-8f2e-e74bd1b9d5c9
      version: -1
      name: Sleep
      description: Sleep for X seconds
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      seconds:
        simple: "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 895
        }
      }
    note: false
    timertriggers: []
  "5":
    id: "5"
    taskid: a44d4ef4-0348-42c6-8fdc-cec1ade54d07
    type: regular
    task:
      id: a44d4ef4-0348-42c6-8fdc-cec1ade54d07
      version: -1
      name: Print
      description: Prints text to war room (Markdown supprted)
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      value:
        simple: Success
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
  "6":
    id: "6"
    taskid: 2eaeafac-c846-47f2-8e81-0f6453a36d67
    type: regular
    task:
      id: 2eaeafac-c846-47f2-8e81-0f6453a36d67
      version: -1
      name: whois
      description: Provides data enrichment for Domains, URLs, and IP addresses.
      script: Whois|||whois
      type: regular
      iscommand: true
      brand: Whois
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      query:
        simple: google.com
      retry-count:
        simple: "5"
      retry-interval:
        simple: "30"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
  "7":
    id: "7"
    taskid: f71a1dfb-c1f0-44e3-815a-97ca0e2cbf25
    type: condition
    task:
      id: f71a1dfb-c1f0-44e3-815a-97ca0e2cbf25
      version: -1
      name: Check results
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: ${Domain.Name}
            iscontext: true
          right:
            value:
              simple: google.com
      - - operator: isEqualString
          left:
            value:
              simple: Domain.Whois.TechAdmin.country
            iscontext: true
          right:
            value:
              simple: US
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
  "8":
    id: "8"
    taskid: b2c28eaf-aa18-44fc-8069-d0d8698a182b
    type: regular
    task:
      id: b2c28eaf-aa18-44fc-8069-d0d8698a182b
      version: -1
      name: Sleep
      description: Sleep for 5 seconds, due to whois rate limit
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      seconds:
        simple: "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
  "9":
    id: "9"
    taskid: 6e15ec68-013c-4042-830b-043a004ae105
    type: regular
    task:
      id: 6e15ec68-013c-4042-830b-043a004ae105
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
  "10":
    id: "10"
    taskid: 87b7f42c-95e1-43e9-844a-92c6e34d6c0a
    type: regular
    task:
      id: 87b7f42c-95e1-43e9-844a-92c6e34d6c0a
      version: -1
      name: domain
      description: Provides data enrichment for domains.
      script: Whois|||domain
      type: regular
      iscommand: true
      brand: Whois
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      domain:
        simple: google.com
      retry-count:
        simple: "5"
      retry-interval:
        simple: "30"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
  "11":
    id: "11"
    taskid: 4afa531c-2722-4208-8c97-2cfdd2ab4b90
    type: condition
    task:
      id: 4afa531c-2722-4208-8c97-2cfdd2ab4b90
      version: -1
      name: Check results
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "12"
      "yes":
      - "15"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: Domain.Whois.QueryStatus
            iscontext: true
          right:
            value:
              simple: Success
      - - operator: isEqualString
          left:
            value:
              simple: Domain.Whois.ExpirationDate
            iscontext: true
          right:
            value:
              simple: 14-02-2021
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
  "12":
    id: "12"
    taskid: da814820-3cff-4af9-8411-822386b97977
    type: regular
    task:
      id: da814820-3cff-4af9-8411-822386b97977
      version: -1
      name: Sleep
      description: Sleep for X seconds
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      seconds:
        simple: "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 2295
        }
      }
    note: false
    timertriggers: []
  "13":
    id: "13"
    taskid: dfd80cbe-119e-4015-88c3-b0fa88865b00
    type: regular
    task:
      id: dfd80cbe-119e-4015-88c3-b0fa88865b00
      version: -1
      name: domain
      description: Provides data enrichment for domains.
      script: Whois|||domain
      type: regular
      iscommand: true
      brand: Whois
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      domain:
        simple: google.co.uk
      retry-count:
        simple: "5"
      retry-interval:
        simple: "30"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 2470
        }
      }
    note: false
    timertriggers: []
  "14":
    id: "14"
    taskid: 8ada3995-f569-4f6f-854d-1364e0c20e02
    type: condition
    task:
      id: 8ada3995-f569-4f6f-854d-1364e0c20e02
      version: -1
      name: Check results
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "15"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: ${Domain.Name}
            iscontext: true
          right:
            value:
              simple: google.co.uk
      - - operator: isEqualString
          left:
            value:
              simple: Domain.Whois.ExpirationDate
            iscontext: true
          right:
            value:
              simple: 14-02-2021
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 2645
        }
      }
    note: false
    timertriggers: []
  "15":
    id: "15"
    taskid: 022c838e-9566-4beb-8fb3-f754fdb538b4
    type: regular
    task:
      id: 022c838e-9566-4beb-8fb3-f754fdb538b4
      version: -1
      name: Print
      description: Prints text to war room (Markdown supprted)
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      value:
        simple: Success
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2820
        }
      }
    note: false
    timertriggers: []
  "16":
    id: "16"
    taskid: c9fad6b5-124d-4590-81cc-26e726ebeb16
    type: regular
    task:
      id: c9fad6b5-124d-4590-81cc-26e726ebeb16
      version: -1
      name: Sleep
      description: Sleep for 5 seconds, due to whois rate limit
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      seconds:
        simple: "10"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2865,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
toversion: 4.1.9
tests:
- No test