id: MicrosoftCloudAppSecurity-Test
version: 9
vcShouldKeepItemLegacyProdMachine: false
name: MicrosoftCloudAppSecurity-Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: dda0771a-bd86-467e-82a8-10000af3f16f
    type: start
    task:
      id: dda0771a-bd86-467e-82a8-10000af3f16f
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 8ae9934a-6d46-4549-8691-efb4c4e2b30a
    type: regular
    task:
      id: 8ae9934a-6d46-4549-8691-efb4c4e2b30a
      version: -1
      name: DeleteContext
      script: DeleteContext
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 200
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: bd1741ad-cace-4719-8268-b20a4d5f870d
    type: regular
    task:
      id: bd1741ad-cace-4719-8268-b20a4d5f870d
      version: -1
      name: microsoft-cas-alert-dismiss-bulk
      script: '|||microsoft-cas-alert-dismiss-bulk'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 380
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: dfd878dc-15d8-48d4-8ce5-183210a7b934
    type: regular
    task:
      id: dfd878dc-15d8-48d4-8ce5-183210a7b934
      version: -1
      name: microsoft-cas-alerts-list
      script: '|||microsoft-cas-alerts-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      alert_id:
        simple: 5f06d71dba4289d0602ba5ac
      customer_filters: {}
      instance: {}
      limit: {}
      resolution_status: {}
      service: {}
      severity: {}
      skip: {}
      username: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 565
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 81cf39d4-d095-418e-813a-f3e44146745e
    type: regular
    task:
      id: 81cf39d4-d095-418e-813a-f3e44146745e
      version: -1
      name: microsoft-cas-alert-resolve-bulk
      script: '|||microsoft-cas-alert-resolve-bulk'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      alert_id: {}
      comment: {}
      customer_filters: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 810
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: cbfb789d-4f37-42ba-8398-d7f4cf2d3ce8
    type: regular
    task:
      id: cbfb789d-4f37-42ba-8398-d7f4cf2d3ce8
      version: -1
      name: microsoft-cas-activities-list
      script: '|||microsoft-cas-activities-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1020
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: 652eb6fc-0a5d-499b-8e0e-225420dc33ff
    type: regular
    task:
      id: 652eb6fc-0a5d-499b-8e0e-225420dc33ff
      version: -1
      name: microsoft-cas-files-list
      script: '|||microsoft-cas-files-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1220
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: ae82130c-e716-4aac-8150-f415773fbad4
    type: regular
    task:
      id: ae82130c-e716-4aac-8150-f415773fbad4
      version: -1
      name: microsoft-cas-users-accounts-list
      script: '|||microsoft-cas-users-accounts-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1440
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: 17175b90-0a69-4d6e-8138-fdbd04b187c7
    type: title
    task:
      id: 17175b90-0a69-4d6e-8138-fdbd04b187c7
      version: -1
      name: Test Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1680
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1695,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
