category: Authentication
commonfields:
  id: MicrosoftCloudAppSecurity
  version: -1
configuration:
- defaultvalue: https://example.net
  display: Server URL (e.g. https://example.net)
  name: url
  required: true
  type: 0
- display: Username
  name: credentials
  required: true
  type: 9
- display: Fetch incidents
  name: isFetch
  required: false
  type: 8
- display: Incident type
  name: incidentType
  required: false
  type: 13
- display: Trust any certificate (not secure)
  name: insecure
  required: false
  type: 8
- display: Use system proxy settings
  name: proxy
  required: false
  type: 8
- display: Incidents Severity
  hidden: false
  name: severity
  options:
  - Law
  - Medium
  - High
  - All
  required: false
  type: 16
description: This is the Hello World integration for getting started.
display: MicrosoftCloudAppSecurity
name: MicrosoftCloudAppSecurity
script:
  commands:
  - arguments:
    - default: false
      defaultValue: '50'
      description: Maximum number of records returned by the request.
      isArray: false
      name: limit
      required: false
      secret: false
    - default: false
      isArray: false
      required: false
      secret: false
    deprecated: false
    description: Hello command - prints hello to anyone
    execution: false
    name: helloworld-say-hello
    outputs:
    - contextPath: hello
      description: Should be Hello **something** here
      type: String
  - deprecated: false
    execution: false
  dockerimage: demisto/python3:3.7.4.2245
  feed: false
  isfetch: true
  longRunning: false
  longRunningPort: false
  runonce: false
  script: '-'
  subtype: python3
  type: python
