category: Authentication
commonfields:
  id: MicrosoftCloudAppSecurity
  version: -1
configuration:
- defaultvalue: https://example.net
  display: Server URL (e.g. https://example.net)
  name: url
  required: true
  type: 0
- display: token
  name: token
  required: true
  type: 4
- display: Fetch incidents
  name: isFetch
  required: false
  type: 8
- display: Incident type
  name: incidentType
  required: false
  type: 13
- display: Trust any certificate (not secure)
  name: insecure
  required: false
  type: 8
- display: Use system proxy settings
  name: proxy
  required: false
  type: 8
- display: Incidents Severity
  hidden: false
  name: severity
  options:
  - Law
  - Medium
  - High
  - All
  required: false
  type: 16
description: This is the Hello World integration for getting started.
display: MicrosoftCloudAppSecurity
name: MicrosoftCloudAppSecurity
script:
  commands:
  - arguments:
    - default: false
      defaultValue: '50'
      description: Maximum number of records returned by the request.
      isArray: false
      name: limit
      required: false
      secret: false
    - default: false
      isArray: false
      required: false
      secret: false
    deprecated: false
    description: Hello command - prints hello to anyone
    execution: false
    name: helloworld-say-hello
    outputs:
    - contextPath: hello
      description: Should be Hello **something** here
      type: String
  - deprecated: false
    execution: false
  - arguments:
    - default: false
      description: Skips the specified number of records.
      isArray: false
      name: skip
      required: false
      secret: false
    - default: false
      defaultValue: '50'
      description: Maximum number of records returned by the request.
      isArray: false
      name: limit
      required: false
      secret: false
    - auto: PREDEFINED
      default: false
      description: The severity of the aler.
      isArray: false
      name: severity
      predefined:
      - Law
      - Medium
      - High
      - All
      required: false
      secret: false
    - default: false
      description: Filter alerts related to the specified service appId.
      isArray: false
      name: service
      required: false
      secret: false
    - default: false
      description: Filter alerts related to the specified instances.
      isArray: false
      name: instance
      required: false
      secret: false
    - auto: PREDEFINED
      default: false
      description: Filter by alert resolution status.
      isArray: false
      name: resolutionStatus
      predefined:
      - Open
      - Dismissed
      - Resolved
      required: false
      secret: false
    - default: false
      description: Filter that the customer chooses for himself.
      isArray: false
      name: Customer filter
      required: false
      secret: false
    - default: false
      description: alert id
      isArray: false
      name: id
      required: false
      secret: false
    deprecated: false
    description: List alerts command - prints list alerts
    execution: false
    name: microsoft-cas-alerts-list
  dockerimage: demisto/python3:3.7.4.2245
  feed: false
  isfetch: true
  longRunning: false
  longRunningPort: false
  runonce: false
  script: '-'
  subtype: python3
  type: python
